[TS-429] Implemented Socket Server for real time chat
TradeShare490/TradeShare pull request #105
Opened 2022-03-13 10:23 UTC by tungleu

will write more detail on how to test

2022-03-13 15:52 UTC, AlyaNaseer requested changes
So cool! Awesome work!

Like you mentioned in your video, there are some things that are not included in your PR so you might change the scope. I'd specify what is actually included and what isn't included in your PR for easy referral.

I'll list below some of the things that remain to do:
- Replace username by name in the chat window and chat menu (**)
- Have the username below the name in the chat window (*)
- Save the messages in database
- The avatar in the chat window seems to be a bit low, but it might be because the row containing the username isn't filled (*)
- Rewrite Cypress tests (**)
- Time since last message

The ones with ** are ones I recommend you do in your PR now since I think it should be required to call this PR complete (especially since you removed the Cypress tests, to make sure we don't forget to add it back, it could be good to do it now). The ones with * are ones that could be an easy fix in this PR as well but I don't consider them as absolutely necessary for the scope of this PR. And of course the DB implementation will be its own thing.

2022-03-13 16:09 UTC, GadoliniumPotassium commented
I can't believe you made snapchat!

2022-03-13 17:18 UTC, itsShaVawn requested changes
In addition to what @AlyaNaseer said: 
![image](https://user-images.githubusercontent.com/49250036/158071213-fdaf5292-951e-40d2-9ec5-a43c003d898f.png)

I would have also liked to see the "New message" button being used in your video.

2022-03-13 17:18 UTC, itsShaVawn commented on src/components/Messages/ChatMenu.vue
> +    //
remove this

2022-03-13 17:18 UTC, itsShaVawn commented on src/components/Messages/Conversation.vue
> +</template>
add new line

2022-03-13 17:18 UTC, itsShaVawn commented on src/components/Messages/Conversation.vue
> +
remove extra line

2022-03-13 17:18 UTC, itsShaVawn commented on src/components/Messages/Conversation.vue
> +<style scoped>
remove

2022-03-13 17:33 UTC, AlyaNaseer commented
> In addition to what @AlyaNaseer said: ![image](https://user-images.githubusercontent.com/49250036/158071213-fdaf5292-951e-40d2-9ec5-a43c003d898f.png)
> 
> I would have also liked to see the "New message" button being used in your video.

I think some of the changes you ask might be difficult in this PR since the DB isn't implemented, but I'm not 100% sure

2022-03-13 17:46 UTC, itsShaVawn commented
> > In addition to what @AlyaNaseer said: ![image](https://user-images.githubusercontent.com/49250036/158071213-fdaf5292-951e-40d2-9ec5-a43c003d898f.png)
> > I would have also liked to see the "New message" button being used in your video.
> 
> I think some of the changes you ask might be difficult in this PR since the DB isn't implemented, but I'm not 100% sure

These have nothing to do with the DB though.

Maybe this will be more clear:

- Circle 1: profile picture and username are misaligned. If anything, the pfp should be centered and not touching the divider.
- Circle 2: the username is breaking because the container is small, but there is ample amount of space for the username to avoid wrapping.
- Circle 3: this is the only one involving the DB, where the message in the circle doesn't appear in the chat window.
- Circle 4: the height of the messaging component doesn't extend to the whole available page.

2022-03-13 20:10 UTC, itsShaVawn commented
u have 3 code smell

2022-03-13 20:12 UTC, tungleu commented
> u have 3 code smell

oops

2022-03-13 20:20 UTC, tungleu commented
> So cool! Awesome work!
> 
> Like you mentioned in your video, there are some things that are not included in your PR so you might change the scope. I'd specify what is actually included and what isn't included in your PR for easy referral.
> 
> I'll list below some of the things that remain to do:
> 
> * Replace username by name in the chat window and chat menu (**)
> * Have the username below the name in the chat window (*)
> * Save the messages in database
> * The avatar in the chat window seems to be a bit low, but it might be because the row containing the username isn't filled (*)
> * Rewrite Cypress tests (**)
> * Time since last message
> 
> The ones with ** are ones I recommend you do in your PR now since I think it should be required to call this PR complete (especially since you removed the Cypress tests, to make sure we don't forget to add it back, it could be good to do it now). The ones with * are ones that could be an easy fix in this PR as well but I don't consider them as absolutely necessary for the scope of this PR. And of course the DB implementation will be its own thing.

since our current conversation model in the back end only has a username field so I'm not able to fetch the name at the moment. For the cypress test i already edited it, I just removed some static data tests

2022-03-13 20:24 UTC, tungleu commented
> > > In addition to what @AlyaNaseer said: ![image](https://user-images.githubusercontent.com/49250036/158071213-fdaf5292-951e-40d2-9ec5-a43c003d898f.png)
> > > I would have also liked to see the "New message" button being used in your video.
> > 
> > 
> > I think some of the changes you ask might be difficult in this PR since the DB isn't implemented, but I'm not 100% sure
> 
> These have nothing to do with the DB though.
> 
> Maybe this will be more clear:
> 
> * Circle 1: profile picture and username are misaligned. If anything, the pfp should be centered and not touching the divider.
> * Circle 2: the username is breaking because the container is small, but there is ample amount of space for the username to avoid wrapping.
> * Circle 3: this is the only one involving the DB, where the message in the circle doesn't appear in the chat window.
> * Circle 4: the height of the messaging component doesn't extend to the whole available page.



> > > In addition to what @AlyaNaseer said: ![image](https://user-images.githubusercontent.com/49250036/158071213-fdaf5292-951e-40d2-9ec5-a43c003d898f.png)
> > > I would have also liked to see the "New message" button being used in your video.
> > 
> > 
> > I think some of the changes you ask might be difficult in this PR since the DB isn't implemented, but I'm not 100% sure
> 
> These have nothing to do with the DB though.
> 
> Maybe this will be more clear:
> 
> * Circle 1: profile picture and username are misaligned. If anything, the pfp should be centered and not touching the divider.
> * Circle 2: the username is breaking because the container is small, but there is ample amount of space for the username to avoid wrapping.
> * Circle 3: this is the only one involving the DB, where the message in the circle doesn't appear in the chat window.
> * Circle 4: the height of the messaging component doesn't extend to the whole available page.

![image](https://user-images.githubusercontent.com/30036024/158077767-db210952-e2e1-4eda-81e2-b58b93753892.png)
temporary removed latest message as this was actually fetch from the backend and i didnt write the new messages into the database and also replace user's name with user's username so that the profile pic wont overflow

2022-03-13 20:57 UTC, AlyaNaseer commented
> > > In addition to what @AlyaNaseer said: ![image](https://user-images.githubusercontent.com/49250036/158071213-fdaf5292-951e-40d2-9ec5-a43c003d898f.png)
> > > I would have also liked to see the "New message" button being used in your video.
> > 
> > 
> > I think some of the changes you ask might be difficult in this PR since the DB isn't implemented, but I'm not 100% sure
> 
> These have nothing to do with the DB though.
> 
> Maybe this will be more clear:
> 
> * Circle 1: profile picture and username are misaligned. If anything, the pfp should be centered and not touching the divider.
> * Circle 2: the username is breaking because the container is small, but there is ample amount of space for the username to avoid wrapping.
> * Circle 3: this is the only one involving the DB, where the message in the circle doesn't appear in the chat window.
> * Circle 4: the height of the messaging component doesn't extend to the whole available page.

The text wrapping is most likely because the "time since last message" isn't displayed

2022-03-13 21:20 UTC, AlyaNaseer commented
The only thing I noticed is now the text box for the text isn't always at the bottom, as the screen gets bigger. You might need to add the "height:100%" I suggested elsewhere too (like in the message window component)

![image](https://user-images.githubusercontent.com/46854444/158079671-bed826c9-d27c-4b1c-b71c-291f67ac7714.png)

Also, I'd add a placeholder for the last message and for the time, just so we know what it'll look like. I'd also append a "@" to the username here: 
![image](https://user-images.githubusercontent.com/46854444/158079705-0cddc523-eb96-4ceb-8766-708fd5c664a0.png)

2022-03-13 21:30 UTC, itsShaVawn commented
> 

the what?

2022-03-13 21:30 UTC, itsShaVawn commented
> > > > In addition to what @AlyaNaseer said: ![image](https://user-images.githubusercontent.com/49250036/158071213-fdaf5292-951e-40d2-9ec5-a43c003d898f.png)
> > > > I would have also liked to see the "New message" button being used in your video.
> > > 
> > > 
> > > I think some of the changes you ask might be difficult in this PR since the DB isn't implemented, but I'm not 100% sure
> > 
> > 
> > These have nothing to do with the DB though.
> > Maybe this will be more clear:
> > 
> > * Circle 1: profile picture and username are misaligned. If anything, the pfp should be centered and not touching the divider.
> > * Circle 2: the username is breaking because the container is small, but there is ample amount of space for the username to avoid wrapping.
> > * Circle 3: this is the only one involving the DB, where the message in the circle doesn't appear in the chat window.
> > * Circle 4: the height of the messaging component doesn't extend to the whole available page.
> 
> The text wrapping is most likely because the "time since last message" isn't displayed

the what?

2022-03-13 21:35 UTC, AlyaNaseer commented
> > > > > In addition to what @AlyaNaseer said: ![image](https://user-images.githubusercontent.com/49250036/158071213-fdaf5292-951e-40d2-9ec5-a43c003d898f.png)
> > > > > I would have also liked to see the "New message" button being used in your video.
> > > > 
> > > > 
> > > > I think some of the changes you ask might be difficult in this PR since the DB isn't implemented, but I'm not 100% sure
> > > 
> > > 
> > > These have nothing to do with the DB though.
> > > Maybe this will be more clear:
> > > 
> > > * Circle 1: profile picture and username are misaligned. If anything, the pfp should be centered and not touching the divider.
> > > * Circle 2: the username is breaking because the container is small, but there is ample amount of space for the username to avoid wrapping.
> > > * Circle 3: this is the only one involving the DB, where the message in the circle doesn't appear in the chat window.
> > > * Circle 4: the height of the messaging component doesn't extend to the whole available page.
> > 
> > 
> > The text wrapping is most likely because the "time since last message" isn't displayed
> 
> the what?

Your Circle 2 text wrapping is most likely due to the fact that the "5m" (time since last message sent) is not visible in this PR
![image](https://user-images.githubusercontent.com/46854444/158080170-124ed4c2-a894-4ff5-9afb-b31141e43693.png)

2022-03-13 22:07 UTC, tungleu commented
> 

![image](https://user-images.githubusercontent.com/30036024/158081233-b0f86525-5bb9-4f66-a428-9e004d3fbcef.png)
Addressed :)

2022-03-14 04:29 UTC, AlyaNaseer approved these changes

2022-03-14 14:15 UTC, itsShaVawn approved these changes
👍🏼

2022-03-14 16:07 UTC, merged