[TS-347] Comparison Tool for My Dashboard and Other Dashboard (without graph)
TradeShare490/TradeShare pull request #107
Opened 2022-03-15 18:14 UTC by AlyaNaseer

Navigate to: /comparison
Click "Click me"
![image](https://user-images.githubusercontent.com/46854444/158443594-9240baa6-5c0e-480b-a5e1-17be4e15858e.png)

Here we see the 5 users, and here it is in the code (pages/ComparisonTool/ComparisonTool.vue):
![image](https://user-images.githubusercontent.com/46854444/158443598-f4147d98-d0f4-4c78-8852-d5e429739712.png)

If we change it to 1 user:
![image](https://user-images.githubusercontent.com/46854444/158443593-b7ccd84c-973d-4946-b04d-209d1b02df2e.png)
![image](https://user-images.githubusercontent.com/46854444/158443597-01a11f0f-3c76-4705-aa05-a9cc32792353.png)

Here are two videos showing the functionality of the modal (each option except for Maximum returns the date range in the console). By default the custom "to" and "from" dates are disabled unless the custom option is selected. Pops up a calendar to choose dates and I added date validation (can't have a "to" date be before the "from" date). 

Cypress tests are also done. For now each of the option tests is kind of trivial but that's because the graph isn't implemented.

The way the custom dates works is as follows:
- if no dates are entered, by default show today's returns
- if "from" date is entered but not "to" date, show date range from "from" date to today
- if "to" date is entered but not "from" date, show all data from beginning to date specified (by default beginning is 1900-01-01)

https://user-images.githubusercontent.com/46854444/158444544-ff049184-a40e-4dd8-81bb-630903605442.mp4
https://user-images.githubusercontent.com/46854444/158444551-dac2c81f-29d9-431e-8a7d-5ab67dad4276.mp4

2022-03-15 19:55 UTC, bowe99 requested changes
Is there a way we could restrict keyboard input on the text boxes because I think I found a way around your constraints 

https://user-images.githubusercontent.com/50396173/158460469-560a558c-20ab-408b-b0b7-e6f63d5704da.mp4

2022-03-15 19:57 UTC, AlyaNaseer commented
> Is there a way we could restrict keyboard input on the text boxes because I think I found a way around your constraints
> 
>  Bug_Trim.mp4

Nice catch, I'll look into that

2022-03-15 21:05 UTC, bowe99 submitted a review, later dismissed
This is great work! Works perfectly now

2022-03-16 03:06 UTC, itsShaVawn requested changes
![image](https://user-images.githubusercontent.com/49250036/158508478-042f7c2c-f87e-4fe2-83ec-3df5d6e58545.png)

Just some small things:

- I would make the button the same style as the "New Item" button for consistency
- Maybe add a bit more margin above the button, it seems a bit close to the container to me
- What exactly does the refresh button do? Or what is it supposed to do? Does it refresh the graph or refresh the filters?

Great work!

2022-03-16 03:06 UTC, itsShaVawn commented on src/components/ComparisonTool/ComparisonModal.vue
> +
no need for the extra space here

2022-03-16 03:06 UTC, itsShaVawn commented on src/components/ComparisonTool/ComparisonModal.vue
> +            <v-card
this can be a one liner

2022-03-16 03:06 UTC, itsShaVawn commented on src/components/ComparisonTool/ComparisonModal.vue
> +  props: {
add an export name

2022-03-16 03:08 UTC, itsShaVawn commented
![image](https://user-images.githubusercontent.com/49250036/158508910-bb17197d-f429-40fe-b392-c69f6349ec5e.png)

I think also for small screens you could display only the colored dots or only dots and first name so it looks cleaner

2022-03-16 03:10 UTC, itsShaVawn commented
![image](https://user-images.githubusercontent.com/49250036/158509016-ad1602af-1863-4d62-8ad3-98fd8863d70a.png)
![image](https://user-images.githubusercontent.com/49250036/158509032-494a54c2-320a-4ae0-8395-d58b649abb03.png)

Maybe some adjustments here for small screens. We can't see the whole calendar or any date that is inputted

2022-03-16 03:13 UTC, itsShaVawn commented
> ![image](https://user-images.githubusercontent.com/49250036/158508910-bb17197d-f429-40fe-b392-c69f6349ec5e.png)
> 
> I think also for small screens you could display only the colored dots or only dots and first name so it looks cleaner

Just another suggestion here, since on this size, the box for the graph is higher than it is wider, this will make the graph look weird. Maybe try bringing the filters and stuff under the graph card. That way the graph would have more space on smaller screens and your filters would also have more width.

2022-03-16 23:05 UTC, itsShaVawn approved these changes
Nice work! 👍🏼

2022-03-16 23:13 UTC, bowe99 approved these changes

2022-03-16 23:13 UTC, merged