[TS-284] Re-integrate username
TradeShare490/TradeShare pull request #65
Opened 2022-01-16 09:03 UTC by tungleu

Brought back username, User can also login with either username or email 
![image](https://user-images.githubusercontent.com/30036024/149653741-ed300852-da4d-4abf-9625-a54efa0a9547.png)

Note: since the backend PR is not merged so you can only test with the local back end, for now, To review this PR, please run the backend code and change the HOST variable in `axios.v1.js` file  to `"//localhost:5000/api/v1"` 

![image](https://user-images.githubusercontent.com/30036024/149653812-e9d30db8-eee9-443a-b3a9-167577dfe62d.png)

2022-01-16 15:51 UTC, GadoliniumPotassium commented
Is this implemented in a way where we can just refer to a props to make each page unique?

2022-01-16 18:33 UTC, Ming424 submitted a review, later dismissed
lgtm, it will definitely facilitate the end user

2022-01-17 03:37 UTC, itsShaVawn requested changes

2022-01-17 03:37 UTC, itsShaVawn commented on src/components/Login/Login.vue
> +          label="Email or username"
```suggestion
          label="Email or Username"
```
Capitalize this

2022-01-17 03:38 UTC, itsShaVawn requested changes
You forgot to add the username to the Other Dashboard, Following, Followers and Messages pages. 
Check Figma to see where the username is on those pages.

2022-01-17 03:38 UTC, itsShaVawn commented
I tried logging into the test user's account with the username and it does not work.
![image](https://user-images.githubusercontent.com/49250036/149703954-4ef0ae54-5cb1-4a68-8942-c629d8725a59.png)
![image](https://user-images.githubusercontent.com/49250036/149703982-699041f1-ea24-45aa-aab2-2d6cf046523d.png)
this ⬆️ does nothing when I click login.
![image](https://user-images.githubusercontent.com/49250036/149704011-c261751e-bdcb-489d-acc9-55a0055de06b.png)
also tried this ⬆️

2022-01-17 03:42 UTC, itsShaVawn commented
I signed up with a new account and the homepage doesn't display the username
![image](https://user-images.githubusercontent.com/49250036/149704538-f1c86f34-94d7-4d99-8c20-9d82947059b2.png)
I also cannot log back in with the username
![image](https://user-images.githubusercontent.com/49250036/149704582-eebc1237-a718-414e-ac75-a8abe9e25353.png)

2022-01-17 14:01 UTC, AlyaNaseer requested changes

2022-01-17 14:01 UTC, AlyaNaseer commented on src/components/SignUp/SignUp.vue
> +            data-cy="userName"
This doesn't follow our coding convention of "firstword-nextword"
```suggestion
            data-cy="user-name"
```

2022-01-17 20:59 UTC, tungleu commented on src/components/SignUp/SignUp.vue
> +        format: (v) => /^(?!.*\.\.)(?!.*\.$)[^\W][\w.]{0,29}$/.test(v) || "No special characters"
the format accepted is a string with a minimum of 4 characters without special characters 🤔

2022-01-17 21:58 UTC, AlyaNaseer commented on src/components/SignUp/SignUp.vue
> +        format: (v) => /^(?!.*\.\.)(?!.*\.$)[^\W][\w.]{0,29}$/.test(v) || "No special characters"
Yeah I know, it's more for if our stakeholders or people look at our code in the future, but if you think it's clear enough, we can leave as-is

2022-01-19 00:14 UTC, AlyaNaseer approved these changes
LGTM

2022-01-21 20:08 UTC, AlyaNaseer submitted a review, later dismissed

2022-01-21 20:55 UTC, itsShaVawn requested changes

2022-01-21 20:55 UTC, itsShaVawn commented on src/components/FollowerFollowing/UserBlock.vue
> +              >{{ this.name }}</v-list-item-title
need to fix indentation here

2022-01-21 20:55 UTC, itsShaVawn commented on src/components/FollowerFollowing/UserBlock.vue
> +            >@{{this.username}}</v-list-item-title
here as well

2022-01-21 20:55 UTC, itsShaVawn commented on src/components/FollowerFollowing/UserBlock.vue
> +
remove extra line

2022-01-21 20:55 UTC, itsShaVawn commented on src/components/FollowerFollowing/UserBlock.vue
>        <v-spacer></v-spacer>
use self closing tag here

2022-01-21 20:55 UTC, itsShaVawn commented on src/components/FollowerFollowing/UserBlock.vue
> +
no space here

2022-01-21 20:55 UTC, itsShaVawn commented on src/components/Login/Login.vue
> +        }catch (e) {
add a space before catch

2022-01-21 20:55 UTC, itsShaVawn commented on src/components/SignUp/SignUp.vue
> +        ></v-text-field>
use a self closing tag + no extra spaces before or after the tags

2022-01-21 20:55 UTC, itsShaVawn commented on src/components/SignUp/SignUp.vue
> +        }catch (e){
space before catch

2022-01-21 20:55 UTC, itsShaVawn commented on src/hooks/useCredential.js
> +
remove extra line

2022-01-21 20:55 UTC, itsShaVawn commented on src/hooks/useCredential.js
> +
remove extra line

2022-01-21 20:55 UTC, itsShaVawn commented on src/hooks/useCredential.js
> +  console.log(
remove console.logs

2022-01-21 21:48 UTC, itsShaVawn approved these changes

2022-01-21 22:06 UTC, AlyaNaseer approved these changes

2022-01-21 22:14 UTC, merged