[TS-203] BUG: Fixed position date and add checker
TradeShare490/TradeShare pull request #72
Opened 2022-01-24 00:23 UTC by Ming424

+ Fix date format for new added position
+ Add checker for input values: Symbol, Position Size, Valid Date (using snackbar for the notification)
![image](https://user-images.githubusercontent.com/37958655/150704392-fc8fe4e3-b9ff-41fa-9cea-d15db804453b.png)
![image](https://user-images.githubusercontent.com/37958655/150704397-5a4929dc-607b-400c-843f-a7636ce819b1.png)

2022-01-24 01:01 UTC, itsShaVawn requested changes

2022-01-24 01:01 UTC, itsShaVawn commented on src/components/Portfolio/Positions.vue
> +            this.snackbarText = "Unvalid input, please verify";
```suggestion
            this.snackbarText = "Invalid input. Please try again.";
```

2022-01-24 01:01 UTC, itsShaVawn commented on src/components/Portfolio/Positions.vue
> +            this.snackbarText = "Unvalid input, please verify";
```suggestion
            this.snackbarText = "Invalid input. Please try again.";
```

2022-01-24 01:03 UTC, Ming424 commented on src/components/Portfolio/Positions.vue
> +            this.snackbarText = "Unvalid input, please verify";
Commited

2022-01-24 01:13 UTC, itsShaVawn submitted a review, later dismissed
Lgtm 👍🏼

2022-01-25 03:12 UTC, Ming424 commented
BLOCK FTM INVESTIGATING THE ISSUE

2022-01-25 06:00 UTC, Ming424 commented
UNBLOCKED

2022-01-25 19:57 UTC, kennguyen0303 approved these changes
lgtm

2022-01-25 20:39 UTC, Ming424 commented
Also delete label component

2022-01-26 00:31 UTC, tungleu approved these changes
I prefer to have users use the calendar for date input instead of typing literal date format string which causes format inconsistency.  Overall the checker works as expected,good job!

2022-01-26 00:31 UTC, merged