[TS-51] Follow List and Follow/Unfollow Action
TradeShare490/TradeShare pull request #94
Opened 2022-02-21 03:33 UTC by Ming424

This PR contains TS-327 and TS-397, move TS-328 to next sprint
![image](https://user-images.githubusercontent.com/37958655/154883372-5718d9d9-6f60-4e4b-981f-bb7e786e11b1.png)

Followings
![image](https://user-images.githubusercontent.com/37958655/154880197-fca63377-eb19-4b43-bf1d-766edd941bcb.png)
Followers
![image](https://user-images.githubusercontent.com/37958655/154880208-52b97628-0959-417a-9909-14e3dbdf5850.png)

Snackbar notification for the success response
![image](https://user-images.githubusercontent.com/37958655/154880261-d5888964-b185-4b0c-b6bb-003d422198fb.png)

When list is empty
![image](https://user-images.githubusercontent.com/37958655/154880387-0a1a03a8-d16f-4f18-8c65-4dbfdf55b0ed.png)

Sidebar (fetch at login, dont know how to refresh, see Issues below)
![image](https://user-images.githubusercontent.com/37958655/154883445-2e4b7f74-7f0e-4179-8383-9ccb4f9b0488.png)

New asset
![image](https://user-images.githubusercontent.com/37958655/154880287-bc7738e4-02c7-4d0b-a8da-61d9822e8c0d.png)

Issue (I think we need a new ticket for these): 
- No profile picture implement, everything will be set to default (above asset)
- Slow when fetching the list
- Not sure how to refresh number in sidebar once follow/unfollow happened
- Remove dummy data, the tests are failing, I commented them out

Current relationship (API https://documenter.getpostman.com/view/10545271/UVe9QU3y#b55383f2-6f80-4271-be4f-a0514a28f0d6)
![image](https://user-images.githubusercontent.com/37958655/154880473-0a50b436-16b0-439a-bc0e-9b8752d113d2.png)

Accounts I use to test
test                 [6204a777f82a1fb5c9f80a1f]
TianMing        [6211cb412ab77bf00f22fd87]
TianMing2      [6211cb5a2ab77bf00f22fd91]
IDNF Pico       [6212d380693803381b1583a6]

HOW TO TEST

Add User ID in Line 41 in UserBlock to debug easier
![image](https://user-images.githubusercontent.com/37958655/154881515-4295458d-b367-4b31-9365-0195cb8fc62f.png)

Copy accessToken once login
![image](https://user-images.githubusercontent.com/37958655/154880767-32fddcfb-14b1-4cf5-ad4b-138a38a0949a.png)

Pasted inside Authorization-Bearer_Token
![image](https://user-images.githubusercontent.com/37958655/154880850-fd320d5d-d5a6-4fed-baf7-7d1a0c055794.png)

Try to follow and unfollow from [Following] list (same logic in [Followers] list, but [Following is easier to restore)
Once follow/unfollow, DO
GET http://localhost:5000/api/v1/following/follows/6204a777f82a1fb5c9f80a1f
To see the list of following match you expectation
![image](https://user-images.githubusercontent.com/37958655/154881175-b6d523fa-6bca-4b43-b917-a56b5c79906a.png)

If you accidently lost a relation, how to follow in postman
- From the same page without refreshing
- POST http://localhost:5000/api/v1/following/follow
- - {
    "actorId": "6204a777f82a1fb5c9f80a1f",
    "targetId": "{ID_YOU_WANT_TO_FOLLOW}"
}

Still fixing the E2E, but i wont affect the testing

2022-02-25 15:36 UTC, AlyaNaseer commented
Wow this is a relatively big PR haha! 

A few things I noted:
![image](https://user-images.githubusercontent.com/46854444/155742230-e25e41a7-39f8-468d-bd52-3ac8254748d6.png)

1. There is too much spacing above and below the text, which is forcing a scroll, which in this case we don't need. You could look at just centering the text vertically so it doesn't make the component bigger
2. I think we should change the text from "Empty List" to "You aren't following anyone"/"You have no followers"
3. In the side menu, if there are no followers/following, it should say 0 instead of "null"
4. Did you remove the search in the following page altogether? Or only when you aren't following anyone?

As for the cypress tests, we'll need to make a decision about what these pages should look like and how they should behave so that we either keep the uncommented code or we remove (we have to make sure not to push it as is as it isn't good programming practices to have that much commented out code)

2022-02-25 15:36 UTC, AlyaNaseer requested changes
See changes mentioned above

2022-02-25 15:39 UTC, AlyaNaseer commented
You've got a failing Cypress test as well 
![image](https://user-images.githubusercontent.com/46854444/155743564-eb0d8518-2820-41d2-add1-baf6e786fda1.png)

2022-03-12 16:38 UTC, itsShaVawn commented on src/pages/Followers/Followers.vue
> +                <v-col>You do not have any follower yet.</v-col>
```suggestion
                <v-col>You do not have any followers yet.</v-col>
```

2022-03-12 16:39 UTC, itsShaVawn requested changes
The side menu doesnt appear for some reason? 
![image](https://user-images.githubusercontent.com/49250036/158026525-27e30803-c79c-4712-bf65-9eb7a46075e4.png)

the following page looks like this?
![image](https://user-images.githubusercontent.com/49250036/158026576-0bfceb0b-562a-4ec9-9478-2953d0f31743.png)

2022-03-12 16:40 UTC, itsShaVawn commented
You also have merge conflicts, code duplication and 2 code smells. The code smells are commented code, so just remove this.

2022-03-12 21:55 UTC, Ming424 commented
> The side menu doesnt appear for some reason? ![image](https://user-images.githubusercontent.com/49250036/158026525-27e30803-c79c-4712-bf65-9eb7a46075e4.png)
> 
> the following page looks like this? ![image](https://user-images.githubusercontent.com/49250036/158026576-0bfceb0b-562a-4ec9-9478-2953d0f31743.png)

Because it auto login, sign off and login will solve the issue.
Following is fixed
![image](https://user-images.githubusercontent.com/37958655/158036423-cde4812b-803e-4376-87c1-92a2e3716c1f.png)

2022-03-12 22:29 UTC, Ming424 commented on src/pages/Followers/Followers.vue
> +                <v-col>You do not have any follower yet.</v-col>
Fixed

2022-03-12 22:31 UTC, Ming424 commented
> Wow this is a relatively big PR haha!
> 
> A few things I noted: ![image](https://user-images.githubusercontent.com/46854444/155742230-e25e41a7-39f8-468d-bd52-3ac8254748d6.png)
> 
> 1. There is too much spacing above and below the text, which is forcing a scroll, which in this case we don't need. You could look at just centering the text vertically so it doesn't make the component bigger
> 2. I think we should change the text from "Empty List" to "You aren't following anyone"/"You have no followers"
> 3. In the side menu, if there are no followers/following, it should say 0 instead of "null"
> 4. Did you remove the search in the following page altogether? Or only when you aren't following anyone? Because I noticed you commented out a lot of cypress tests
> 
> As for the cypress tests, we'll need to make a decision about what these pages should look like and how they should behave so that we either keep the uncommented code or we remove (we have to make sure not to push it as is as it isn't good programming practices to have that much commented out code)

+ For num 0 
![image](https://user-images.githubusercontent.com/37958655/158037250-f8a81274-8abd-42ca-8050-6aca63dacb0e.png)
+ For empty list, was obsessed with vertical center, but have problem with, so it will be bind to top
![image](https://user-images.githubusercontent.com/37958655/158037261-2a3a8ee8-aabf-411c-9f7b-01ba3d9202af.png)
+ Cypress is fixed

2022-03-13 00:18 UTC, AlyaNaseer commented
Idk why but for some reason I'm having a hard time pulling your branch, it doesn't seem to be updated. But from the video, everything looks good to me

2022-03-13 00:20 UTC, AlyaNaseer approved these changes

2022-03-13 03:24 UTC, itsShaVawn commented
I'm having some issues with the unfollowing part and the counter. I'll show a video demonstrating the issue.

2022-03-13 03:27 UTC, itsShaVawn commented
[2022-03-12 22-22-04.zip](https://github.com/TradeShare490/TradeShare/files/8238917/2022-03-12.22-22-04.zip)

2022-03-13 04:54 UTC, AlyaNaseer approved these changes

2022-03-13 16:06 UTC, AlyaNaseer approved these changes

2022-03-13 16:41 UTC, itsShaVawn approved these changes
Nice work!

2022-03-13 16:45 UTC, merged