[TS-331] Account Preferences
TradeShare490/TradeShare pull request #98
Opened 2022-02-26 04:55 UTC by itsShaVawn

Added the page for the account preferences

After:
![image](https://user-images.githubusercontent.com/49250036/155829581-c3f63967-9b00-45ba-813c-de250a432f3d.png)
![image](https://user-images.githubusercontent.com/49250036/155829646-61063124-9899-4c62-8dc7-2e5d30881a3c.png)
![image](https://user-images.githubusercontent.com/49250036/155829653-a0706251-f767-4b50-b68b-50fc1ee69e78.png)

Before: 
![image](https://user-images.githubusercontent.com/49250036/155829629-dfa7833a-e5d3-46fb-a0a3-9be67445f15a.png)

2022-03-06 23:50 UTC, AlyaNaseer requested changes
Looks good, though I noticed this weird overflow at the end: 
![image](https://user-images.githubusercontent.com/46854444/156947659-05849b0d-4300-4060-83cb-18d95015de77.png)

Otherwise, looks great!

2022-03-06 23:53 UTC, AlyaNaseer commented
Also, there seems to be a double space here 
![image](https://user-images.githubusercontent.com/46854444/156947795-ba687e47-96b2-4879-b349-54eaa17a1e96.png)

and here
![image](https://user-images.githubusercontent.com/46854444/156947807-feaf9271-d2f4-4045-b9d1-cc3d71be0ac6.png)

2022-03-07 00:25 UTC, itsShaVawn commented
> Looks good, though I noticed this weird overflow at the end: ![image](https://user-images.githubusercontent.com/46854444/156947659-05849b0d-4300-4060-83cb-18d95015de77.png)
> 
> Otherwise, looks great!

I think I fixed this in my other PR.

2022-03-07 00:26 UTC, AlyaNaseer approved these changes

2022-03-07 01:46 UTC, tungleu approved these changes

2022-03-07 02:01 UTC, merged